/**
 * Action Tracking Service
 *
 * CRUD operations for action items generated by the action recommender.
 * Persists to Supabase `di_action_items` table with localStorage fallback.
 */

import { supabase } from '../infra/supabaseClient';
import { ACTION_STATUS } from '../../domains/risk/actionRecommender';

const TABLE = 'di_action_items';
const LOCAL_KEY = 'di_action_items_local';

// ── Supabase persistence ────────────────────────────────────────────────────

async function trySupabase(fn) {
  try {
    return await fn();
  } catch {
    return null;
  }
}

// ── Local fallback ──────────────────────────────────────────────────────────

function getLocalActions() {
  try {
    return JSON.parse(localStorage.getItem(LOCAL_KEY) || '[]');
  } catch {
    return [];
  }
}

function setLocalActions(items) {
  try {
    localStorage.setItem(LOCAL_KEY, JSON.stringify(items.slice(0, 500)));
  } catch {
    // Quota exceeded — silent
  }
}

// ── Public API ──────────────────────────────────────────────────────────────

/**
 * Save a batch of action items from a risk run.
 */
export async function saveActions(runId, actions, userId) {
  if (!actions || actions.length === 0) return;

  const rows = actions.map(a => ({
    id: a.id,
    run_id: runId,
    sku: a.sku,
    plant_id: a.plant_id,
    action_type: a.type,
    title: a.title,
    description: a.description,
    urgency: a.urgency,
    priority_score: a.priority,
    reason_code: a.reason_code,
    expected_impact_usd: a.expected_impact_usd || 0,
    owner: a.owner,
    status: a.status || ACTION_STATUS.OPEN,
    due_date: a.due_date,
    user_id: userId,
    created_at: new Date().toISOString(),
  }));

  const result = await trySupabase(() =>
    supabase.from(TABLE).upsert(rows, { onConflict: 'id' })
  );

  if (!result) {
    // Fallback to local storage
    const existing = getLocalActions();
    const idSet = new Set(existing.map(e => e.id));
    const merged = [...existing, ...rows.filter(r => !idSet.has(r.id))];
    setLocalActions(merged);
  }
}

/**
 * Get all open/in-progress actions for a user.
 */
export async function getOpenActions(userId) {
  const result = await trySupabase(async () => {
    const { data, error } = await supabase
      .from(TABLE)
      .select('*')
      .eq('user_id', userId)
      .in('status', [ACTION_STATUS.OPEN, ACTION_STATUS.IN_PROGRESS])
      .order('priority_score', { ascending: false })
      .limit(200);
    if (error) throw error;
    return data;
  });

  if (result) return result;

  // Fallback
  return getLocalActions()
    .filter(a => a.user_id === userId && (a.status === ACTION_STATUS.OPEN || a.status === ACTION_STATUS.IN_PROGRESS))
    .sort((a, b) => (b.priority_score || 0) - (a.priority_score || 0))
    .slice(0, 200);
}

/**
 * Get all actions for a specific run.
 */
export async function getActionsByRun(runId) {
  const result = await trySupabase(async () => {
    const { data, error } = await supabase
      .from(TABLE)
      .select('*')
      .eq('run_id', runId)
      .order('priority_score', { ascending: false });
    if (error) throw error;
    return data;
  });

  if (result) return result;
  return getLocalActions()
    .filter(a => a.run_id === runId)
    .sort((a, b) => (b.priority_score || 0) - (a.priority_score || 0));
}

/**
 * Update the status of an action item.
 */
export async function updateActionStatus(actionId, status) {
  const result = await trySupabase(async () => {
    const { error } = await supabase
      .from(TABLE)
      .update({ status, updated_at: new Date().toISOString() })
      .eq('id', actionId);
    if (error) throw error;
    return true;
  });

  if (!result) {
    const local = getLocalActions();
    const idx = local.findIndex(a => a.id === actionId);
    if (idx >= 0) {
      local[idx].status = status;
      local[idx].updated_at = new Date().toISOString();
      setLocalActions(local);
    }
  }
}

/**
 * Assign an owner and optional due date to an action.
 */
export async function assignAction(actionId, owner, dueDate = null) {
  const update = { owner, updated_at: new Date().toISOString() };
  if (dueDate) update.due_date = dueDate;

  const result = await trySupabase(async () => {
    const { error } = await supabase
      .from(TABLE)
      .update(update)
      .eq('id', actionId);
    if (error) throw error;
    return true;
  });

  if (!result) {
    const local = getLocalActions();
    const idx = local.findIndex(a => a.id === actionId);
    if (idx >= 0) {
      Object.assign(local[idx], update);
      setLocalActions(local);
    }
  }
}

/**
 * Dismiss an action (mark as dismissed).
 */
export async function dismissAction(actionId) {
  return updateActionStatus(actionId, ACTION_STATUS.DISMISSED);
}

/**
 * Get action summary stats for the ops dashboard.
 */
export async function getActionSummary(userId) {
  const actions = await getOpenActions(userId);
  const byUrgency = { critical: 0, high: 0, medium: 0, low: 0 };
  const byType = {};

  actions.forEach(a => {
    byUrgency[a.urgency] = (byUrgency[a.urgency] || 0) + 1;
    byType[a.action_type] = (byType[a.action_type] || 0) + 1;
  });

  return {
    total_open: actions.length,
    by_urgency: byUrgency,
    by_type: byType,
    top_actions: actions.slice(0, 5),
  };
}
