import { test, expect } from '@playwright/test';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { setupSupabaseMock } from './global-setup.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function readEnvVar(varName) {
  try {
    const content = fs.readFileSync(path.join(__dirname, '..', '..', '.env.local'), 'utf8');
    const match = content.match(new RegExp(`^${varName}=(.+)$`, 'm'));
    return match ? match[1].trim() : null;
  } catch {
    return null;
  }
}

const SUPABASE_URL =
  process.env.VITE_SUPABASE_URL || readEnvVar('VITE_SUPABASE_URL') || '';

function buildMockReviewTask({ id, title, workflowType, daysAgo, artifactLabel }) {
  const endedAt = new Date(Date.now() - daysAgo * 24 * 60 * 60 * 1000).toISOString();
  return {
    id,
    employee_id: 'emp-review-1',
    title,
    description: `${title} generated by Aiden for manager review.`,
    status: 'review_hold',
    priority: 'medium',
    updated_at: endedAt,
    due_at: null,
    input_context: {
      workflow_type: workflowType,
      template_id: workflowType,
    },
    loop_state: {
      steps: [
        { name: workflowType, status: 'done', retry_count: 0, summary: `${workflowType} completed.` },
        { name: 'synthesize', status: 'review_hold', retry_count: 1, summary: 'Executive summary awaiting approval.' },
      ],
    },
    ai_employee_runs: [
      {
        id: `run-${id}`,
        status: 'succeeded',
        summary: `${title} is ready for review.`,
        ended_at: endedAt,
        started_at: endedAt,
        step_index: 1,
        step_name: 'synthesize',
        retry_count: 1,
        error_message: null,
        artifact_refs: [
          {
            type: 'report_json',
            label: artifactLabel,
            run_id: `run-${id}`,
            data: {
              executive_summary: `${title} summary`,
              action_items: ['Monitor supplier lead time', 'Approve adjusted replenishment plan'],
            },
          },
        ],
      },
    ],
  };
}

test.describe('Review Center', () => {
  test.use({ storageState: 'e2e/.auth/storage-state.json' });
  let currentTasks = [];

  test.beforeEach(async ({ page }) => {
    await setupSupabaseMock(page);
    currentTasks = [
      buildMockReviewTask({
        id: 'task-review-1',
        title: 'Weekly Risk Scan Alpha',
        workflowType: 'risk',
        daysAgo: 2,
        artifactLabel: 'Risk summary JSON',
      }),
      buildMockReviewTask({
        id: 'task-review-2',
        title: 'Weekly Risk Scan Beta',
        workflowType: 'risk',
        daysAgo: 1,
        artifactLabel: 'Risk detail JSON',
      }),
      buildMockReviewTask({
        id: 'task-review-3',
        title: 'Weekly Risk Scan Gamma',
        workflowType: 'risk',
        daysAgo: 3,
        artifactLabel: 'Risk exception JSON',
      }),
    ];

    if (SUPABASE_URL) {
      await page.route(`${SUPABASE_URL}/rest/v1/ai_employees*`, async (route) => {
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify([{ id: 'emp-review-1' }]),
        });
      });

      await page.route(`${SUPABASE_URL}/rest/v1/ai_employee_tasks*`, async (route) => {
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(currentTasks),
        });
      });
    }
  });

  test('renders pending review queue and detail panels', async ({ page }) => {
    const errors = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto('/employees/review');
    await page.waitForLoadState('networkidle', { timeout: 15000 });

    await expect(page.getByText('Review Center')).toBeVisible();
    await expect(page.getByText('3 pending')).toBeVisible();

    await expect(page.getByRole('button', { name: /Weekly Risk Scan Alpha/i })).toBeVisible();
    await expect(page.getByRole('button', { name: /Weekly Risk Scan Beta/i })).toBeVisible();
    await expect(page.getByRole('button', { name: /Weekly Risk Scan Gamma/i })).toBeVisible();

    await expect(page.getByText('Weekly Risk Scan Alpha generated by Aiden for manager review.')).toBeVisible();
    await expect(page.getByText('Manager-ready output')).toBeVisible();
    await expect(page.getByText('Risk Memo')).toBeVisible();
    await expect(page.getByRole('button', { name: 'Deliverable' })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Evidence (1)' })).toBeVisible();
    await expect(page.getByText('Weekly Risk Scan Alpha summary')).toBeVisible();
    await expect(page.getByRole('button', { name: 'Approve' })).toBeVisible();

    await page.getByRole('button', { name: /Weekly Risk Scan Beta/i }).click();
    await expect(page.getByText('Weekly Risk Scan Beta summary')).toBeVisible();

    await page.getByRole('button', { name: 'Evidence (1)' }).click();
    await expect(page.getByText('Risk detail JSON')).toBeVisible();

    await page.getByRole('button', { name: /Risk detail JSON/i }).click();
    await expect(page.getByText(/Weekly Risk Scan Beta summary/i)).toBeVisible();

    await expect(page.locator('#vite-error-overlay')).toHaveCount(0);
    expect(errors.filter((e) => !e.includes('ResizeObserver'))).toHaveLength(0);
  });

  test('reselects the first task when the review queue changes after refresh', async ({ page }) => {
    await page.goto('/employees/review');
    await page.waitForLoadState('networkidle', { timeout: 15000 });

    await expect(page.getByText('Weekly Risk Scan Alpha generated by Aiden for manager review.')).toBeVisible();

    currentTasks = [
      buildMockReviewTask({
        id: 'task-review-4',
        title: 'Weekly Risk Scan Delta',
        workflowType: 'risk',
        daysAgo: 1,
        artifactLabel: 'Delta risk JSON',
      }),
      buildMockReviewTask({
        id: 'task-review-5',
        title: 'Weekly Risk Scan Epsilon',
        workflowType: 'risk',
        daysAgo: 2,
        artifactLabel: 'Epsilon risk JSON',
      }),
    ];

    await page.getByTitle('Refresh').click();
    await page.waitForLoadState('networkidle', { timeout: 15000 });

    await expect(page.getByText('2 pending')).toBeVisible();
    await expect(page.getByRole('button', { name: /Weekly Risk Scan Delta/i })).toBeVisible();
    await expect(page.getByText('Weekly Risk Scan Delta summary')).toBeVisible();
    await expect(page.getByRole('button', { name: 'Approve' })).toBeVisible();
  });
});
