-- Decision Intelligence Step 5
-- Reuse / memory / learning loop tables for Workflow A

DO $$
BEGIN
  IF to_regclass('public.di_dataset_profiles') IS NULL THEN
    RAISE EXCEPTION 'Missing dependency table public.di_dataset_profiles. Run sql/migrations/di_dataset_profiles.sql first.';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.di_contract_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  fingerprint TEXT NOT NULL,
  workflow TEXT NOT NULL,
  contract_json JSONB NOT NULL,
  quality_score NUMERIC NOT NULL DEFAULT 0.0,
  usage_count INT NOT NULL DEFAULT 0,
  last_used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_di_contract_templates_user_workflow_fingerprint
  ON public.di_contract_templates(user_id, workflow, fingerprint);

CREATE INDEX IF NOT EXISTS idx_di_contract_templates_user_last_used
  ON public.di_contract_templates(user_id, last_used_at DESC);

ALTER TABLE public.di_contract_templates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own contract templates" ON public.di_contract_templates;
CREATE POLICY "Users can view own contract templates"
  ON public.di_contract_templates FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own contract templates" ON public.di_contract_templates;
CREATE POLICY "Users can insert own contract templates"
  ON public.di_contract_templates FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own contract templates" ON public.di_contract_templates;
CREATE POLICY "Users can update own contract templates"
  ON public.di_contract_templates FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own contract templates" ON public.di_contract_templates;
CREATE POLICY "Users can delete own contract templates"
  ON public.di_contract_templates FOR DELETE
  USING (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS public.di_run_settings_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  workflow TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  settings_json JSONB NOT NULL,
  quality_score NUMERIC NOT NULL DEFAULT 0.0,
  usage_count INT NOT NULL DEFAULT 0,
  last_used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_di_run_settings_templates_user_workflow_fingerprint
  ON public.di_run_settings_templates(user_id, workflow, fingerprint);

CREATE INDEX IF NOT EXISTS idx_di_run_settings_templates_user_last_used
  ON public.di_run_settings_templates(user_id, last_used_at DESC);

ALTER TABLE public.di_run_settings_templates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own run settings templates" ON public.di_run_settings_templates;
CREATE POLICY "Users can view own run settings templates"
  ON public.di_run_settings_templates FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own run settings templates" ON public.di_run_settings_templates;
CREATE POLICY "Users can insert own run settings templates"
  ON public.di_run_settings_templates FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own run settings templates" ON public.di_run_settings_templates;
CREATE POLICY "Users can update own run settings templates"
  ON public.di_run_settings_templates FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own run settings templates" ON public.di_run_settings_templates;
CREATE POLICY "Users can delete own run settings templates"
  ON public.di_run_settings_templates FOR DELETE
  USING (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS public.di_dataset_similarity_index (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  dataset_profile_id BIGINT NOT NULL REFERENCES public.di_dataset_profiles(id) ON DELETE CASCADE,
  fingerprint TEXT NOT NULL,
  signature_json JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_di_dataset_similarity_index_user_profile
  ON public.di_dataset_similarity_index(user_id, dataset_profile_id);

CREATE INDEX IF NOT EXISTS idx_di_dataset_similarity_index_user_fingerprint
  ON public.di_dataset_similarity_index(user_id, fingerprint);

ALTER TABLE public.di_dataset_similarity_index ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own dataset similarity index" ON public.di_dataset_similarity_index;
CREATE POLICY "Users can view own dataset similarity index"
  ON public.di_dataset_similarity_index FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own dataset similarity index" ON public.di_dataset_similarity_index;
CREATE POLICY "Users can insert own dataset similarity index"
  ON public.di_dataset_similarity_index FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own dataset similarity index" ON public.di_dataset_similarity_index;
CREATE POLICY "Users can update own dataset similarity index"
  ON public.di_dataset_similarity_index FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own dataset similarity index" ON public.di_dataset_similarity_index;
CREATE POLICY "Users can delete own dataset similarity index"
  ON public.di_dataset_similarity_index FOR DELETE
  USING (auth.uid() = user_id);

-- Ensure PostgREST picks up new tables/policies immediately
NOTIFY pgrst, 'reload schema';
