-- Decision-Intelligence Step 2
-- Forecast run tracking + artifacts for chat-first workflow

DO $$
BEGIN
  IF to_regclass('public.di_dataset_profiles') IS NULL THEN
    RAISE EXCEPTION 'Missing dependency table public.di_dataset_profiles. Run sql/migrations/di_dataset_profiles.sql first.';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.di_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  dataset_profile_id BIGINT NOT NULL REFERENCES public.di_dataset_profiles(id) ON DELETE CASCADE,
  workflow TEXT NOT NULL,
  stage TEXT NOT NULL,
  status TEXT NOT NULL,
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,
  error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_di_runs_status CHECK (status IN ('queued', 'running', 'succeeded', 'failed'))
);

CREATE INDEX IF NOT EXISTS idx_di_runs_user_created
  ON public.di_runs(user_id, created_at DESC);

ALTER TABLE public.di_runs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own di runs" ON public.di_runs;
CREATE POLICY "Users can view own di runs"
  ON public.di_runs FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own di runs" ON public.di_runs;
CREATE POLICY "Users can insert own di runs"
  ON public.di_runs FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own di runs" ON public.di_runs;
CREATE POLICY "Users can update own di runs"
  ON public.di_runs FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own di runs" ON public.di_runs;
CREATE POLICY "Users can delete own di runs"
  ON public.di_runs FOR DELETE
  USING (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS public.di_run_artifacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES public.di_runs(id) ON DELETE CASCADE,
  artifact_type TEXT NOT NULL,
  artifact_json JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_di_run_artifacts_run_type
  ON public.di_run_artifacts(run_id, artifact_type);

ALTER TABLE public.di_run_artifacts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own di run artifacts" ON public.di_run_artifacts;
CREATE POLICY "Users can view own di run artifacts"
  ON public.di_run_artifacts FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.di_runs r
      WHERE r.id = di_run_artifacts.run_id
        AND r.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can insert own di run artifacts" ON public.di_run_artifacts;
CREATE POLICY "Users can insert own di run artifacts"
  ON public.di_run_artifacts FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.di_runs r
      WHERE r.id = di_run_artifacts.run_id
        AND r.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can update own di run artifacts" ON public.di_run_artifacts;
CREATE POLICY "Users can update own di run artifacts"
  ON public.di_run_artifacts FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM public.di_runs r
      WHERE r.id = di_run_artifacts.run_id
        AND r.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.di_runs r
      WHERE r.id = di_run_artifacts.run_id
        AND r.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can delete own di run artifacts" ON public.di_run_artifacts;
CREATE POLICY "Users can delete own di run artifacts"
  ON public.di_run_artifacts FOR DELETE
  USING (
    EXISTS (
      SELECT 1
      FROM public.di_runs r
      WHERE r.id = di_run_artifacts.run_id
        AND r.user_id = auth.uid()
    )
  );

-- Ensure PostgREST picks up new tables/policies immediately
NOTIFY pgrst, 'reload schema';
