-- Decision Intelligence Step 4
-- Workflow step-level tracking for resumable/replayable orchestration

DO $$
BEGIN
  IF to_regclass('public.di_runs') IS NULL THEN
    RAISE EXCEPTION 'Missing dependency table public.di_runs. Run sql/migrations/di_runs_and_artifacts.sql first.';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.di_run_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES public.di_runs(id) ON DELETE CASCADE,
  step TEXT NOT NULL,
  status TEXT NOT NULL,
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,
  error_code TEXT,
  error_message TEXT,
  input_ref JSONB,
  output_ref JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_di_run_steps_status CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'skipped')),
  CONSTRAINT uq_di_run_steps_run_step UNIQUE (run_id, step)
);

CREATE INDEX IF NOT EXISTS idx_di_run_steps_run_step
  ON public.di_run_steps(run_id, step);

ALTER TABLE public.di_run_steps ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own di run steps" ON public.di_run_steps;
CREATE POLICY "Users can view own di run steps"
  ON public.di_run_steps FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.di_runs r
      WHERE r.id = di_run_steps.run_id
        AND r.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can insert own di run steps" ON public.di_run_steps;
CREATE POLICY "Users can insert own di run steps"
  ON public.di_run_steps FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.di_runs r
      WHERE r.id = di_run_steps.run_id
        AND r.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can update own di run steps" ON public.di_run_steps;
CREATE POLICY "Users can update own di run steps"
  ON public.di_run_steps FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM public.di_runs r
      WHERE r.id = di_run_steps.run_id
        AND r.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.di_runs r
      WHERE r.id = di_run_steps.run_id
        AND r.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can delete own di run steps" ON public.di_run_steps;
CREATE POLICY "Users can delete own di run steps"
  ON public.di_run_steps FOR DELETE
  USING (
    EXISTS (
      SELECT 1
      FROM public.di_runs r
      WHERE r.id = di_run_steps.run_id
        AND r.user_id = auth.uid()
    )
  );

-- Ensure PostgREST picks up new tables/policies immediately
NOTIFY pgrst, 'reload schema';
