-- Solver run telemetry for planning observability
-- Tracks solve_time, infeasible/timeout rates, and async queue wait linkage.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.solver_runs_telemetry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id UUID NOT NULL DEFAULT gen_random_uuid(),
  telemetry_run_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  source TEXT NOT NULL,
  run_id BIGINT,
  job_id UUID,
  status TEXT,
  termination_reason TEXT,
  engine TEXT,
  objective TEXT,
  solve_time_ms INT,
  queue_wait_ms INT,
  infeasible_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  input_fingerprint TEXT,
  input_shape JSONB NOT NULL DEFAULT '{}'::jsonb,
  env TEXT,
  git_sha TEXT,
  contract_version TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_solver_runs_telemetry_event_type
    CHECK (event_type IN ('started', 'finished', 'summary')),
  CONSTRAINT ck_solver_runs_telemetry_solve_time_ms
    CHECK (solve_time_ms IS NULL OR solve_time_ms >= 0),
  CONSTRAINT ck_solver_runs_telemetry_queue_wait_ms
    CHECK (queue_wait_ms IS NULL OR queue_wait_ms >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_solver_runs_telemetry_summary_once
  ON public.solver_runs_telemetry (telemetry_run_id, event_type)
  WHERE event_type = 'summary';

CREATE INDEX IF NOT EXISTS idx_solver_runs_telemetry_time
  ON public.solver_runs_telemetry (occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_solver_runs_telemetry_event_time
  ON public.solver_runs_telemetry (event_type, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_solver_runs_telemetry_engine_status_time
  ON public.solver_runs_telemetry (engine, status, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_solver_runs_telemetry_run_job
  ON public.solver_runs_telemetry (run_id, job_id, occurred_at DESC);

NOTIFY pgrst, 'reload schema';
