-- ============================================================
-- Approved Plan Write-Back: baseline tables for approved plans
-- ============================================================

-- Table 1: approved_plan_orders
-- Stores denormalized plan_table rows from approved plans.
-- Becomes the queryable baseline for subsequent planning runs.

CREATE TABLE IF NOT EXISTS public.approved_plan_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  run_id bigint NOT NULL,
  approval_id text NOT NULL,
  dataset_profile_id bigint,

  sku text NOT NULL,
  plant_id text,
  order_date date NOT NULL,
  arrival_date date NOT NULL,
  order_qty numeric NOT NULL CHECK (order_qty >= 0),

  approved_at timestamptz NOT NULL DEFAULT now(),
  approved_by uuid NOT NULL,
  superseded_at timestamptz,
  is_active boolean NOT NULL DEFAULT TRUE,

  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_apo_user_active
  ON public.approved_plan_orders(user_id, is_active) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_apo_run
  ON public.approved_plan_orders(run_id);
CREATE INDEX IF NOT EXISTS idx_apo_sku_plant
  ON public.approved_plan_orders(sku, plant_id);
CREATE INDEX IF NOT EXISTS idx_apo_dataset_profile
  ON public.approved_plan_orders(dataset_profile_id, approved_at DESC) WHERE is_active = TRUE;

ALTER TABLE public.approved_plan_orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own approved plan orders" ON public.approved_plan_orders;
CREATE POLICY "Users can view own approved plan orders"
  ON public.approved_plan_orders FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own approved plan orders" ON public.approved_plan_orders;
CREATE POLICY "Users can insert own approved plan orders"
  ON public.approved_plan_orders FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own approved plan orders" ON public.approved_plan_orders;
CREATE POLICY "Users can update own approved plan orders"
  ON public.approved_plan_orders FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

COMMENT ON TABLE public.approved_plan_orders IS
  'Denormalized approved plan orders. Becomes the baseline for subsequent planning runs.';
COMMENT ON COLUMN public.approved_plan_orders.is_active IS
  'TRUE = current approved baseline; FALSE = superseded by a later approval.';


-- Table 2: inventory_targets
-- Stores inventory projection targets from approved plans.

CREATE TABLE IF NOT EXISTS public.inventory_targets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  run_id bigint NOT NULL,
  approval_id text NOT NULL,
  dataset_profile_id bigint,

  sku text NOT NULL,
  plant_id text,
  target_date date NOT NULL,
  target_inventory numeric NOT NULL,
  baseline_inventory numeric,
  expected_demand numeric NOT NULL DEFAULT 0,
  expected_stockout_units numeric NOT NULL DEFAULT 0,
  planned_inbound numeric NOT NULL DEFAULT 0,
  open_po_inbound numeric NOT NULL DEFAULT 0,

  approved_at timestamptz NOT NULL DEFAULT now(),
  approved_by uuid NOT NULL,
  superseded_at timestamptz,
  is_active boolean NOT NULL DEFAULT TRUE,

  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_it_user_active
  ON public.inventory_targets(user_id, is_active) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_it_run
  ON public.inventory_targets(run_id);
CREATE INDEX IF NOT EXISTS idx_it_sku_plant
  ON public.inventory_targets(sku, plant_id);
CREATE INDEX IF NOT EXISTS idx_it_dataset_profile
  ON public.inventory_targets(dataset_profile_id, approved_at DESC) WHERE is_active = TRUE;

ALTER TABLE public.inventory_targets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own inventory targets" ON public.inventory_targets;
CREATE POLICY "Users can view own inventory targets"
  ON public.inventory_targets FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own inventory targets" ON public.inventory_targets;
CREATE POLICY "Users can insert own inventory targets"
  ON public.inventory_targets FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own inventory targets" ON public.inventory_targets;
CREATE POLICY "Users can update own inventory targets"
  ON public.inventory_targets FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

COMMENT ON TABLE public.inventory_targets IS
  'Approved inventory targets from plan projections. Used as baseline for subsequent planning runs.';


-- RPC: write_approved_plan_baseline
-- Atomically supersedes previous baselines and inserts new ones.

CREATE OR REPLACE FUNCTION write_approved_plan_baseline(
  p_run_id bigint,
  p_approval_id text,
  p_dataset_profile_id bigint,
  p_plan_orders jsonb,
  p_inventory_targets jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
  v_now timestamptz := now();
  v_orders_inserted int := 0;
  v_targets_inserted int := 0;
  v_superseded_orders int := 0;
  v_superseded_targets int := 0;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object('success', FALSE, 'error', 'Not authenticated');
  END IF;

  -- Supersede previous active baselines for this dataset_profile
  IF p_dataset_profile_id IS NOT NULL THEN
    UPDATE public.approved_plan_orders
    SET is_active = FALSE, superseded_at = v_now
    WHERE user_id = v_user_id
      AND dataset_profile_id = p_dataset_profile_id
      AND is_active = TRUE;
    GET DIAGNOSTICS v_superseded_orders = ROW_COUNT;

    UPDATE public.inventory_targets
    SET is_active = FALSE, superseded_at = v_now
    WHERE user_id = v_user_id
      AND dataset_profile_id = p_dataset_profile_id
      AND is_active = TRUE;
    GET DIAGNOSTICS v_superseded_targets = ROW_COUNT;
  END IF;

  -- Insert approved plan orders
  INSERT INTO public.approved_plan_orders (
    user_id, run_id, approval_id, dataset_profile_id,
    sku, plant_id, order_date, arrival_date, order_qty,
    approved_at, approved_by, is_active
  )
  SELECT
    v_user_id,
    p_run_id,
    p_approval_id,
    p_dataset_profile_id,
    (r->>'sku')::text,
    NULLIF(r->>'plant_id', ''),
    (r->>'order_date')::date,
    (r->>'arrival_date')::date,
    (r->>'order_qty')::numeric,
    v_now,
    v_user_id,
    TRUE
  FROM jsonb_array_elements(p_plan_orders) AS r;
  GET DIAGNOSTICS v_orders_inserted = ROW_COUNT;

  -- Insert inventory targets
  INSERT INTO public.inventory_targets (
    user_id, run_id, approval_id, dataset_profile_id,
    sku, plant_id, target_date, target_inventory, baseline_inventory,
    expected_demand, expected_stockout_units, planned_inbound, open_po_inbound,
    approved_at, approved_by, is_active
  )
  SELECT
    v_user_id,
    p_run_id,
    p_approval_id,
    p_dataset_profile_id,
    (r->>'sku')::text,
    NULLIF(r->>'plant_id', ''),
    (r->>'date')::date,
    COALESCE((r->>'with_plan')::numeric, 0),
    (r->>'without_plan')::numeric,
    COALESCE((r->>'demand')::numeric, 0),
    COALESCE((r->>'stockout_units')::numeric, 0),
    COALESCE((r->>'inbound_plan')::numeric, 0),
    COALESCE((r->>'inbound_open_pos')::numeric, 0),
    v_now,
    v_user_id,
    TRUE
  FROM jsonb_array_elements(p_inventory_targets) AS r;
  GET DIAGNOSTICS v_targets_inserted = ROW_COUNT;

  RETURN jsonb_build_object(
    'success', TRUE,
    'orders_inserted', v_orders_inserted,
    'targets_inserted', v_targets_inserted,
    'superseded_orders', v_superseded_orders,
    'superseded_targets', v_superseded_targets,
    'run_id', p_run_id,
    'approval_id', p_approval_id
  );
END;
$$;

GRANT EXECUTE ON FUNCTION write_approved_plan_baseline TO authenticated;
