"""
MCP Tool Catalog — Python-side loader for the auto-generated MCP tool catalog.

Reads mcp-tool-catalog.json (generated by scripts/export-mcp-catalog.js)
and provides typed access + role-based filtering for the MCP server.
"""

import json
import os
import logging
from typing import Any

logger = logging.getLogger(__name__)

# ── Catalog path ──────────────────────────────────────────────────────────────

_CATALOG_PATH = os.path.join(
    os.path.dirname(__file__),
    "..", "..", "..", "openclaw", "mcp-tool-catalog.json",
)

# ── Agent role → category filter ──────────────────────────────────────────────

ROLE_FILTERS: dict[str, set[str]] = {
    "forecast": {
        "core_planning", "analytics", "monitoring", "utility", "data_access",
    },
    "procurement": {
        "core_planning", "negotiation", "cost_revenue", "scenario",
        "utility", "data_access",
    },
    "risk": {
        "risk", "monitoring", "analytics", "scenario", "utility", "data_access",
    },
    # No filter → all tools
}

# ── Catalog class ─────────────────────────────────────────────────────────────


class MCPToolCatalog:
    """Loads and serves MCP tool definitions from the JSON catalog."""

    def __init__(self, catalog_path: str | None = None):
        path = catalog_path or os.path.abspath(_CATALOG_PATH)
        try:
            with open(path, "r", encoding="utf-8") as f:
                raw = json.load(f)
        except FileNotFoundError:
            logger.warning(
                "MCP catalog not found at %s — run 'node scripts/export-mcp-catalog.js' first",
                path,
            )
            raw = {"tools": [], "version": "0.0.0", "tool_count": 0}

        self.version: str = raw.get("version", "0.0.0")
        self.tools: list[dict[str, Any]] = raw.get("tools", [])
        self._by_name: dict[str, dict[str, Any]] = {
            t["name"]: t for t in self.tools
        }
        logger.info(
            "MCP catalog loaded: %d tools, version %s", len(self.tools), self.version
        )

    def get_tool(self, name: str) -> dict[str, Any] | None:
        """Get a single MCP tool definition by name (e.g. 'di_run_forecast')."""
        return self._by_name.get(name)

    def list_tools(self, role: str | None = None) -> list[dict[str, Any]]:
        """
        List MCP tool definitions, optionally filtered by agent role.

        Returns MCP-spec-compliant tool objects (name, description, inputSchema).
        """
        if not role or role not in ROLE_FILTERS:
            return [self._to_mcp_spec(t) for t in self.tools]

        allowed_cats = ROLE_FILTERS[role]
        return [
            self._to_mcp_spec(t)
            for t in self.tools
            if t.get("_di_meta", {}).get("category") in allowed_cats
        ]

    def get_routing_info(self, tool_name: str) -> dict[str, Any] | None:
        """Get DI routing metadata for a tool call."""
        tool = self._by_name.get(tool_name)
        if not tool:
            return None
        return tool.get("_di_meta", {})

    @staticmethod
    def _to_mcp_spec(tool: dict[str, Any]) -> dict[str, Any]:
        """Strip internal _di_meta from tool definition for MCP protocol responses."""
        return {
            "name": tool["name"],
            "description": tool["description"],
            "inputSchema": tool["inputSchema"],
        }


# ── Singleton ─────────────────────────────────────────────────────────────────

_catalog_instance: MCPToolCatalog | None = None


def get_catalog() -> MCPToolCatalog:
    """Get or create the singleton catalog instance."""
    global _catalog_instance
    if _catalog_instance is None:
        _catalog_instance = MCPToolCatalog()
    return _catalog_instance
